# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="powerlevel10k/powerlevel10k"

# DEFAULT Editor
export EDITOR='vim'

# Add homebrew binaries to the path.
export PATH="/usr/local/bin:${PATH?}"

# Force certain more-secure behaviours from homebrew
export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_CASK_OPTS=--require-sha

# Load ruby shims
eval "$(rbenv init -)"
eval "$(nodenv init -)"

# Prefer GNU binaries to Macintosh binaries.
export PATH="/usr/local/opt/coreutils/libexec/gnubin:${PATH}"

# Add AWS CLI to PATH
export PATH="/usr/local/opt/awscli@1/bin:$PATH"

# Point GOPATH to our go sources
export GOPATH="${HOME?}/go"
export PATH=$PATH:$GOPATH/bin

# Tell the devenv vm to mount $GOPATH/src rather than just dd-go
export MOUNT_ALL_GO_SRC=1

# store key in the login keychain instead of aws-vault managing a hidden keychain
export AWS_VAULT_KEYCHAIN_NAME=login

# tweak session times so you don't have to re-enter passwords every 5min
export AWS_SESSION_TTL=24h
export AWS_ASSUME_ROLE_TTL=1h

export FZF_DEFAULT_OPTS="--history='$HOME/.fzf_history'"

export TO_STAGING_QUIET_ON_MERGE='false'
export TO_STAGING_NOTIFY_BEFORE_MERGE='true'

export NODE_OPTIONS="--max-old-space-size=4096"

export DISABLE_VERSION_CHECK=True

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# Plugins
plugins=(git zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

# unalias the garbage that comes with oh-my-zsh
unalias -m '*'

# arrow keys for moving around words. This is currently for mac only
bindkey '^[[1;3D' backward-word
bindkey '^[[1;3C' forward-word

# make history nice
setopt inc_append_history
setopt share_history
setopt hist_ignore_dups
setopt hist_ignore_space

. ~/dotfiles/shell/k8s_aliases.sh

# get all functions
. ~/dotfiles/shell/zsh_functions

# BE AT END
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
source ~/dotfiles/shell/p10k.zsh
